DROP TABLE IF EXISTS image;

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file TEXT UNIQUE NOT NULL,
  shirt BOOLEAN,
  top BOOLEAN,
  sweater BOOLEAN,
  cardigan BOOLEAN,
  jacket BOOLEAN,
  vest BOOLEAN,
  pants BOOLEAN,
  shorts BOOLEAN,
  skirt BOOLEAN,
  coat BOOLEAN,
  dress BOOLEAN,
  jumpsuit BOOLEAN,
  cape BOOLEAN,
  glasses BOOLEAN,
  hat BOOLEAN,
  headband BOOLEAN,
  tie BOOLEAN,
  glove BOOLEAN,
  watch BOOLEAN,
  belt BOOLEAN,
  sock BOOLEAN,
  shoe BOOLEAN,
  bag BOOLEAN,
  scarf BOOLEAN,
  hood BOOLEAN
);