DROP TABLE IF EXISTS image;

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file TEXT UNIQUE NOT NULL,
  shirt INTEGER,
  top INTEGER,
  sweater INTEGER,
  cardigan INTEGER,
  jacket INTEGER,
  vest INTEGER,
  pants INTEGER,
  shorts INTEGER,
  skirt INTEGER,
  coat INTEGER,
  dress INTEGER,
  jumpsuit INTEGER,
  cape INTEGER,
  glasses INTEGER,
  hat INTEGER,
  headband INTEGER,
  tie INTEGER,
  glove INTEGER,
  watch INTEGER,
  belt INTEGER,
  sock INTEGER,
  shoe INTEGER,
  bag INTEGER,
  scarf INTEGER,
  hood INTEGER
);